version: 2

models:
  - name: dim_events_agg
    columns:
      - name: user_guid
        tests:
          - unique:
              severity: warn
          - not_null
      - name: total_sessions
      - name: total_add_cart
      - name: total_page_view
      - name: total_delet_from_cart
      - name: total_checkout
      - name: total_package_shipped

  - name: fact_page_views
    columns:
      - name: event_id
        tests:
          - unique:
              severity: warn
          - not_null
      - name: event_guid 
      - name: session_guid
      - name: user_guid
      - name: event_type
      - name: page_url
      - name: events_created_at_utc
